services:
  db:
    image: postgres:15
    container_name: calendar-db
    environment:
      POSTGRES_USER: maxvays
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: shared_calendar_dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: calendar-backend
    environment:
      DATABASE_URL: "postgresql://maxvays:supersecret@db:5432/shared_calendar_dev"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && npm run dev"

volumes:
  db-data:
