services:
  db:
    image: postgres:15
    container_name: calendar-db
    environment:
      POSTGRES_USER: maxvays
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: shared_calendar_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./shared-calendar-backend
    container_name: calendar-backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://maxvays:supersecret@db:5432/shared_calendar_dev
    volumes:
      - ./shared-calendar-backend:/app
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && npm run dev"

  frontend:
    build:
      context: ./frontend
    container_name: calendar-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - app

volumes:
  db-data:
  frontend_node_modules:
